### ISSUE TITLE
Sync request

### ISSUE THREAD

**Issue by danigarciaalva** [orhanobut/wasp#110]
Is there a way to implement Synchronous request? I really need it.

**Comment by orhanobut** [comment]
Unfortunately currently we don't have this option, yet. But would be great to add it actually, I'll also need this feature. We'll do some major changes very soon and we will also add this feature.

**Comment by danigarciaalva** [comment]
So much thank you, Many users will be appreciate this feature, great library! Mock Rules!!

**Comment by orhanobut** [comment]
I'm happy to hear this, thanks!
I've added sync option with v1.12, will be available in 1 hour probably in maven
