### ISSUE TITLE
[question] when using Observables how can I fetch statusCode

### ISSUE THREAD

**Issue by riinav** [orhanobut/wasp#129]
Basically I want to see the statusCode which http returns, but we return a boolean as a callback from api.

```
@Headers({ "content-type:application/json"  })
@POST("/login.php")
Observable<Boolean> signup(@Query("fullname") String fullName, @Query("email") String email);


if (response.getStatusCode() == 200 && httpPostResponse.getStatus().equalsIgnoreCase("success")) {
    // do something useful
}
```

**Comment by orhanobut** [comment]
By using observables, you can't see response unfortunately, the work around would be to use callback and create your own observable

**Comment by riinav** [comment]
Thanks for the quick reply

yeah, that's what I currently do...
