### ISSUE TITLE
how to parse an array without root

### ISSUE THREAD

**Issue by imdatcandan** [orhanobut/wasp#130]
I couldn't parse a json array without root like below api. If I add a root as Mock data, I can do it easily but no root, no response :D Is it possible to do it thanks to Wasp?
http://api.goeuro.com/api/v2/position/suggest/de/izmir

**Comment by orhanobut** [comment]
This should work out of box actually, have you tried with List interface?
```java
List<YourType> list = request.execute();
```
or async/rx

how did you define your end points?

**Comment by imdatcandan** [comment]
I couldnt understand what you mean with List interface. I tried it with mock data by adding jsonobject like { goEuroList:[bla bla]}. However, how can I write a response class according to given json? List<MyModelClass> ____; what should be blank? Do you have any idea?  

I defined my endpoints like below.
@GET("/{term}")
    void goEuro(@Path("term") String term, Callback<GoEuroResponse> callback);

     waspService =  new Wasp.Builder(this)
                .setEndpoint("http://api.goeuro.com/api/v2/position/suggest/de")
                .enableCookies(CookiePolicy.ACCEPT_ALL)
                .setLogLevel(LogLevel.FULL)
                .setNetworkMode(NetworkMode.LIVE)
                .build()
                .create(WaspService.class);

**Comment by orhanobut** [comment]
The endpoint returns list, thus callback should have List as well. If you try like below, I think the problem will be solved :)

```java
@GET("/{term}")
void goEuro(@Path("term") String term, Callback<List<GoEuroResponse>> callback);
```

**Comment by imdatcandan** [comment]
It's done, thank you so much for your time and interest :)

**Comment by orhanobut** [comment]
:+1:
