### ISSUE TITLE
mode selection via builder

### ISSUE THREAD

**Issue by orhanobut** [orhanobut/wasp#35]
Client should be able to select the mode such as Mode.MOCK etc. We need this feature in order to select the mocking or the real implementation. Deleting each mock annotation would take time and add them back will be frustrating. 

I suggest the following implementation:

- In the builder we can introduce a new method which <code>setMode()</code>
- setMode method should accept <code>Mode.MOCK, Mode.LIVE.</code>  
- default mode should be LIVE.

**Comment by kardeslik** [comment]
NetworkMode added with MOCK and LIVE (which is default) types.
