### ISSUE TITLE
Uploading big files

### ISSUE THREAD

**Issue by orhanobut** [orhanobut/wasp#36]
We should introduce File class in order to upload/download big files. This can stay for now but in the future we should think and discuss about it.

Wasp.File

**Comment by iraycd** [comment]
Why?

**Comment by orhanobut** [comment]
Currently cannot focus on extra features unfortunately. We will focus on network part (json) for now.

**Comment by iraycd** [comment]
Okay. But, should have added it to milestone v1.2 versions.
