### ISSUE TITLE
Cancel Request

### ISSUE THREAD

**Issue by orhanobut** [orhanobut/wasp#38]
Client should be able to cancel the specific request or requests in a very easy way. We should really discuss about this carefully. 

Please consider following items for the suggestions:

- We don't want to make the logic complex, the steps should be really easy for the client. 
- The solution should follow the design principles. Decoupling is really important for us, we don't want to rely only volley since it's just a network stack that we use for now.

**Comment by adrienleroy** [comment]
As explain in the pull request I need to be able to cancel request ( when activity stop or is destroy for exemple). To do that i have added a new Tag that you should add to each method's signature you want to be able to cancel for exemple :
@GET("/repos/{user}/{repo}")
    void fetchRepo(
          @Path("user") String user,
          @Path("repo") String repo,
          @Tag String tag,
          CallBack<List<Repo>> callBack
    );

Then to cancel a request you have to call the network which is exposed by the service this way

myService.getNetworkStack().cancellRequest(myTag)

**Comment by werwe** [comment]
waspRequest = myService.someCall(body,callback);
waspRequest.cancel();

**Comment by orhanobut** [comment]
@werwe This looks a good idea

**Comment by orhanobut** [comment]
added in v1.11 version
