### ISSUE TITLE
shows wrong image while actual image is loading

### ISSUE THREAD

**Issue by farukcankaya** [orhanobut/wasp#43]
I have many images in recyclerview. If scrolls to bottom fastly when the application is opened, imageview shows wrong image while actual image is loading. Generally it shows image loaded in previous imageview. When the actual image is loaded, it shows correct image. But it's bad.

A loading spinner should be shown while image is loading.

**Comment by orhanobut** [comment]
Thank you for the bug report. I'll check it asap.

**Comment by orhanobut** [comment]
I assume that image view already has been set with an image, right? Progress spinner would put too much overhead for these operations. The best approach would be to use default image method to set an image while it's loading or blank.

**Comment by orhanobut** [comment]
I'm on this issue.

**Comment by orhanobut** [comment]
fixed in v1.7
