### ISSUE TITLE
The sample stopped when LISTVIEW&RECYCLERVIEW clicked 

### ISSUE THREAD

**Issue by RoyaAoki** [orhanobut/wasp#85]
java.lang.ClassCastException: com.orhanobut.wasp.WaspOkHttpStack cannot be cast to com.android.volley.toolbox.HttpStack
            at com.orhanobut.wasp.VolleyImageNetworkHandler.<init>(VolleyImageNetworkHandler.java:28)

    this.requestQueue = Volley.newRequestQueue(context, (HttpStack) httpStack);
should become 

    this.requestQueue = Volley.newRequestQueue(context, httpStack.getHttpStack());

?

**Comment by kardeslik** [comment]
Yes you are right.
Will be fixed in the next release.

**Comment by orhanobut** [comment]
fixed in 1.9
