### ISSUE TITLE
Support Post application/x-www-form-urlencoded 

### ISSUE THREAD

**Issue by ghost** [orhanobut/wasp#91]

**Comment by Metaphore** [comment]
I'm very exciting about this project and like what it provides on top of retrofit, but it's very lack of this feature. It's almost unusable with any REST Api that contains even one get request with x-www-form-urlencoded params. Is there any plans on it in a future?

**Comment by orhanobut** [comment]
@Metaphore Currently we are working on all missing features. I think in a few days we can share the roadmap.

**Comment by orhanobut** [comment]
added in v1.11 version

**Comment by Metaphore** [comment]
Awesome, thanks a lot!
