### ISSUE TITLE
404 wiki page (http://orhanobut.github.io/wasp/)

### ISSUE THREAD

**Issue by kevinkl** [orhanobut/wasp#98]
Hey guys,

I use the wasp framework for the first time and I wanted to check out the wiki that you mention in your README.md (url = http://orhanobut.github.io/wasp/). But this page is offline, is their another url for the wiki page?

**Comment by orhanobut** [comment]
@kevinkl 
All documentation is moved to the github (readme.md). We deleted the website. It is exactly the same with the readme

**Comment by kevinkl** [comment]
ok thank you
