### ISSUE TITLE
WaspError should include info about Exceptions coming from Volley

### ISSUE THREAD

**Issue by kardeslik** [orhanobut/wasp#99]
For example, when TimeoutError occurs we could not know the exception is due to time out because all we get from Wasp is a WaspError with status code 0 and null message.

**Comment by Shivakumar546** [comment]
Same problem with UnknownHostException. Please handle error codes

**Comment by orhanobut** [comment]
Let's have this one as top priority, I am also having some issues with this.

**Comment by cutiko** [comment]
If you are reading this you might find this explanation for error 0 interesting https://github.com/orhanobut/wasp/issues/139
